perf(imageData): Use 🖼 ImageData directly (#29)
* perf(imageData): Use 🖼 ImageData directly

- Initial changes to switch to a single Array (most of the code uses Arrays of Arrays).
- Removes the 3d matrix creation (`Array.<Array<Array<Number>>>`) for canvas data and uses ImageData directly instead
- Updates dependencies
- Removes `fixme` task since it's already checked by code climate
- Removes unreliable test

* perf(structure): 🏹 Use array, not array of arrays

Prior implementation used arrays of arrays which were simpler but ~30-40% slower that accessing
a single array directly

BREAKING CHANGE: ssim_map now outputs an object of the form { data, width, height} where data is a
single array instead of an array of arrays. Closes #30

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -1,8 +1,9 @@
 machine:
   node:
-    version: 6.9.1
+    version: 7.0.0
   environment:
-    NODE_CURRENT: 6.9.1
+    NODE_CURRENT: 7.0.0
+    NODE_6: 6.1.0
     NODE_5: 5.7.0
     NODE_012: 0.12.9
 general:
@@ -10,6 +11,8 @@ general:
     - "dist"
     - "coverage"
 dependencies:
+  cache_directories:
+    - node_modules
   pre:
     - sudo apt-get update
     - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ libgnome-keyring-dev
@@ -18,19 +21,13 @@ dependencies:
 test:
   override:
     - npm run build
-    - |
-        # only on master, run integration tests on multiple node versions
-        if [ master == $CIRCLE_BRANCH ]; then
-
-          # `canvas` needs a different install depending on the node version in use.
-          nvm use $NODE_012 && rm -rf node_modules && npm i && npm run e2e:ivc || exit 1
-          nvm use $NODE_5 && rm -rf node_modules && npm i && npm run e2e:ivc || exit 1
-
-          # Clean up and switch back to current node version
-          nvm use $NODE_CURRENT && rm -rf node_modules && npm i
-          npm run e2e || exit 1
-        fi
-    - npm run fixme        # Make sure there are no lingering TODOs
+    # `canvas` needs a different install depending on the node version in use.
+    - nvm use $NODE_012 && rm -rf node_modules && npm i && npm run e2e:ivc || exit 1
+    - nvm use $NODE_5 && rm -rf node_modules && npm i && npm run e2e:ivc || exit 1
+    - nvm install $NODE_6 && rm -rf node_modules && npm i && npm run e2e:ivc || exit 1
+    # Clean up and switch back to current node version
+    - nvm use $NODE_CURRENT && rm -rf node_modules && npm i
+    - npm run e2e || exit 1
     - npm run lint         # Ensure all code adheres to the styleguide
     - npm run docs:check   # Validate documentation using inchjs
     - npm run cover        # Report test coverage locally
