test(unit): Ensure correct status reporting of nvm tests
- Properly log multiple node versions status
- Add `Promise` polyfill for old versions of node
- Removes flaky perf unit test. Performance needs to be revisited in general

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -1,6 +1,11 @@
 machine:
   node:
     version: 6.7.0
+  environment:
+    NODE_CURRENT: 6.7.0
+    NODE_5: 5.7.0
+    NODE_012: 0.12.9
+    NODE_010: 0.10.42
 general:
   artifacts:
     - "dist"
@@ -11,25 +16,29 @@ dependencies:
 test:
   override:
     - npm run build
+    - |
+        # only on master, run integration tests on multiple node versions
+        if [ master == $CIRCLE_BRANCH ]; then
+
+          # `canvas` needs a different install depending on the node version in use.
+          nvm install $NODE_010 && rm -rf node_modules && npm install --loglevel silent && npm run test:e2e || exit 1
+          nvm use $NODE_012 && rm -rf node_modules && npm install --loglevel silent && npm run test:e2e || exit 1
+          nvm use $NODE_5 && rm -rf node_modules && npm install --loglevel silent && npm run test:e2e || exit 1
+
+          # Clean up and switch back to current node version
+          nvm use $NODE_CURRENT && rm -rf node_modules && npm install --loglevel silent
+        fi
     - npm run test:e2e
     - npm run fixme
     - npm run lint
     - npm run docs
     - npm run codeclimate
     - cp -R coverage/* $CIRCLE_TEST_REPORTS
-    - |
-        if [ master == $CIRCLE_BRANCH ]; then
-          nvm install 0.10.42 && nvm use 0.10.42 && bash ci/e2e.sh
-          nvm install 0.12.2 && nvm use 0.12.2 && bash ci/e2e.sh
-          nvm install 5.12.0 && nvm use 5.12.0 && bash ci/e2e.sh
-        fi
 deployment:
   publish:
     owner: obartra
     branch: master
     commands:
-      - rm -rf node_modules
-      - npm install
       - npm run build
       - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
       - npm publish || exit 0
